//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class objects {
    
    private objectsCamera[] camerasField;
    
    private objectsMicrophone[] microphonesField;
    
    private objectsFloorplan[] floorplansField;
    
    private objectsCommand[] remotecommandsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("camera", IsNullable=false)]
    public objectsCamera[] cameras {
        get {
            return this.camerasField;
        }
        set {
            this.camerasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("microphone", IsNullable=false)]
    public objectsMicrophone[] microphones {
        get {
            return this.microphonesField;
        }
        set {
            this.microphonesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("floorplan", IsNullable=false)]
    public objectsFloorplan[] floorplans {
        get {
            return this.floorplansField;
        }
        set {
            this.floorplansField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("command", IsNullable=false)]
    public objectsCommand[] remotecommands {
        get {
            return this.remotecommandsField;
        }
        set {
            this.remotecommandsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCamera {
    
    private objectsCameraSettings settingsField;
    
    private objectsCameraFtp ftpField;
    
    private objectsCameraDetector detectorField;
    
    private objectsCameraRecorder recorderField;
    
    private objectsCameraAlerts alertsField;
    
    private objectsCameraNotifications notificationsField;
    
    private objectsCameraSchedule scheduleField;

    private objectsCameraPtzschedule ptzscheduleField;
    
    private int idField;
    
    private string nameField;
    
    private string descriptionField;

    private string directoryField;
    
    private int xField;
    
    private int yField;

    private bool flipxField;

    private bool flipyField;

    private bool rotate90Field;

    private int widthField;
    
    private int heightField;
   
    private string resolutionField;
    
    private int ptzField;

    private int ptzentryindexField;

    private int newrecordingcountField;

    private string decodekeyField;

    

    /// <remarks/>
    public objectsCameraPtzschedule ptzschedule
    {
        get {
            return this.ptzscheduleField;
        }
        set {
            this.ptzscheduleField = value;
        }
    }

    /// <remarks/>
    public objectsCameraSettings settings {
        get {
            return this.settingsField;
        }
        set {
            this.settingsField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraFtp ftp {
        get {
            return this.ftpField;
        }
        set {
            this.ftpField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraDetector detector {
        get {
            return this.detectorField;
        }
        set {
            this.detectorField = value;
        }
    }

    
    /// <remarks/>
    public objectsCameraRecorder recorder {
        get {
            return this.recorderField;
        }
        set {
            this.recorderField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraAlerts alerts {
        get {
            return this.alertsField;
        }
        set {
            this.alertsField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraNotifications notifications {
        get {
            return this.notificationsField;
        }
        set {
            this.notificationsField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraSchedule schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string decodekey
    {
        get
        {
            return this.decodekeyField;
        }
        set
        {
            this.decodekeyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string directory
    {
        get
        {
            return this.directoryField;
        }
        set
        {
            this.directoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool flipy
    {
        get
        {
            return this.flipyField;
        }
        set
        {
            this.flipyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool flipx
    {
        get
        {
            return this.flipxField;
        }
        set
        {
            this.flipxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool rotate90
    {
        get
        {
            return this.rotate90Field;
        }
        set
        {
            this.rotate90Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resolution {
        get {
            return this.resolutionField;
        }
        set {
            this.resolutionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ptz {
        get {
            return this.ptzField;
        }
        set {
            this.ptzField = value;
        }
    }

     /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ptzentryindex
    {
        get {
            return this.ptzentryindexField;
        }
        set {
            this.ptzentryindexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int newrecordingcount
    {
        get
        {
            return this.newrecordingcountField;
        }
        set
        {
            this.newrecordingcountField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class objectsCameraPtzschedule
{

    private objectsCameraPtzscheduleEntry[] entriesField;

    private bool activeField;
    private bool suspendField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
    public objectsCameraPtzscheduleEntry[] entries
    {
        get
        {
            return this.entriesField;
        }
        set
        {
            this.entriesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool suspend
    {
        get
        {
            return this.suspendField;
        }
        set
        {
            this.suspendField = value;
        }
    }

    
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class objectsCameraPtzscheduleEntry
{

    private string commandField;

    private System.DateTime timeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string command
    {
        get
        {
            return this.commandField;
        }
        set
        {
            this.commandField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "time")]
    public System.DateTime time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraSettings {
    
    private int sourceindexField;
    
    private string codecField;
    
    private string videosourcestringField;
    
    private string loginField;
    
    private string passwordField;
    
    private string useragentField;
    
    private bool suppressnoiseField;

    private int audioportField;

    private string audiomodelField;

    private string audioipField;

    private string audiousernameField;

    private string audiopasswordField;

    private bool usehttp10Field;
    
    private bool activeField;

    private bool notifyondisconnectField;
    
    private int frameintervalField;

    private int framerateField;
    
    private string smsnumberField;
    
    private string emailaddressField;
    
    private string ffmpegField;
    
    private bool deleteaviField;
    
    private int micpairField;

    private string maskimageField;

    private string timestampformatterField;
    
    private int timestamplocationField;

    private decimal timestampoffsetField;

    private int desktopresizewidthField;

    private int desktopresizeheightField;

    private string desktopareaField;

    private bool resizeField;
    
    private objectsCameraSettingsYoutube youtubeField;

    private string vlcargsField;

    private bool ptzflipxField;

    private bool ptzflipyField;

    private bool ptzrotate90Field;

    private bool ptzautotrackField;

    private bool ptzautohomeField;

    private string ptzchannelField;

    private int maxframerateField;

    private int maxframeraterecordField;

    private int ptztimetohomeField;

    private int timestampfontsizeField;

    private int ptzautohomedelayField;

    private string namevaluesettingsField;

    private string ptzusernameField;

    private string ptzpasswordField;

    private bool forcebasicField;

    private string ptzautohomecommandField;

    private string ptzurlbaseField;

    private int reconnectintervalField;

    private int ptzautotrackmodeField;

    private bool ptzautotrackreverseField;

    private string accessgroupsField;

    private int crossbarindexField;

    private bool desktopmouseField;

    private string cookiesField;

    /// <remarks/>
    public string cookies
    {
        get
        {
            return this.cookiesField;
        }
        set
        {
            this.cookiesField = value;
        }
    }

    /// <remarks/>
    public int crossbarindex
    {
        get
        {
            return this.crossbarindexField;
        }
        set
        {
            this.crossbarindexField = value;
        }
    }
    
    /// <remarks/>
    public decimal timestampoffset
    {
        get
        {
            return this.timestampoffsetField;
        }
        set
        {
            this.timestampoffsetField = value;
        }
    } 
   
    /// <remarks/>
    public bool forcebasic
    {
        get
        {
            return this.forcebasicField;
        }
        set
        {
            this.forcebasicField = value;
        }
    }

    /// <remarks/>
    public string ptzusername
    {
        get
        {
            return this.ptzusernameField;
        }
        set
        {
            this.ptzusernameField = value;
        }
    }

    /// <remarks/>
    public string ptzpassword
    {
        get
        {
            return this.ptzpasswordField;
        }
        set
        {
            this.ptzpasswordField = value;
        }
    }

    /// <remarks/>
    public string audiousername
    {
        get
        {
            return this.audiousernameField;
        }
        set
        {
            this.audiousernameField = value;
        }
    }

    /// <remarks/>
    public string audiopassword
    {
        get
        {
            return this.audiopasswordField;
        }
        set
        {
            this.audiopasswordField = value;
        }
    }
    

    /// <remarks/>
    public int ptzautohomedelay
    {
        get
        {
            return this.ptzautohomedelayField;
        }
        set
        {
            this.ptzautohomedelayField = value;
        }
    }
    
    
    /// <remarks/>
    public string accessgroups
    {
        get
        {
            return this.accessgroupsField;
        }
        set
        {
            this.accessgroupsField = value;
        }
    }
    
    /// <remarks/>
    public int ptzautotrackmode
    {
        get
        {
            return this.ptzautotrackmodeField;
        }
        set
        {
            this.ptzautotrackmodeField = value;
        }
    }
    
    /// <remarks/>
    public int reconnectinterval
    {
        get
        {
            return this.reconnectintervalField;
        }
        set
        {
            this.reconnectintervalField = value;
        }
    }
    

    /// <remarks/>
    public int sourceindex {
        get {
            return this.sourceindexField;
        }
        set {
            this.sourceindexField = value;
        }
    }
    
    /// <remarks/>
    public string codec {
        get {
            return this.codecField;
        }
        set {
            this.codecField = value;
        }
    }
    
    /// <remarks/>
    public string videosourcestring {
        get {
            return this.videosourcestringField;
        }
        set {
            this.videosourcestringField = value;
        }
    }
    
    /// <remarks/>
    public string login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }

    public string namevaluesettings
    {
        get { return this.namevaluesettingsField; }
        set { this.namevaluesettingsField = value; }
    }
    
    /// <remarks/>
    public string useragent {
        get {
            return this.useragentField;
        }
        set {
            this.useragentField = value;
        }
    }
    
    /// <remarks/>
    public bool suppressnoise {
        get {
            return this.suppressnoiseField;
        }
        set {
            this.suppressnoiseField = value;
        }
    }

    /// <remarks/>
    public int audioport
    {
        get {
            return this.audioportField;
        }
        set {
            this.audioportField = value;
        }
    }

    /// <remarks/>
    public string audiomodel
    {
        get
        {
            return this.audiomodelField;
        }
        set
        {
            this.audiomodelField = value;
        }
    }

    /// <remarks/>
    public string audioip
    {
        get
        {
            return this.audioipField;
        }
        set
        {
            this.audioipField = value;
        }
    }
    
    /// <remarks/>
    public bool usehttp10
    {
        get {
            return this.usehttp10Field;
        }
        set {
            this.usehttp10Field = value;
        }
    }

    

    /// <remarks/>
    public bool ptzflipx
    {
        get
        {
            return this.ptzflipxField;
        }
        set
        {
            this.ptzflipxField = value;
        }
    }

    /// <remarks/>
    public bool ptzflipy
    {
        get
        {
            return this.ptzflipyField;
        }
        set
        {
            this.ptzflipyField = value;
        }
    }

    /// <remarks/>
    public bool ptzrotate90
    {
        get
        {
            return this.ptzrotate90Field;
        }
        set
        {
            this.ptzrotate90Field = value;
        }
    }
    
    /// <remarks/>
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }

    /// <remarks/>
    public bool notifyondisconnect
    {
        get {
            return this.notifyondisconnectField;
        }
        set {
            this.notifyondisconnectField = value;
        }
    }    
    
    /// <remarks/>
    public int frameinterval {
        get {
            return this.frameintervalField;
        }
        set {
            this.frameintervalField = value;
        }
    }

    /// <remarks/>
    public int maxframerate
    {
        get
        {
            return this.maxframerateField;
        }
        set
        {
            this.maxframerateField = value;
        }
    }

    /// <remarks/>
    public int maxframeraterecord
    {
        get
        {
            return this.maxframeraterecordField;
        }
        set
        {
            this.maxframeraterecordField = value;
        }
    }

    /// <remarks/>
    public int framerate
    {
        get
        {
            return this.framerateField;
        }
        set
        {
            this.framerateField = value;
        }
    }
    
    /// <remarks/>
    public string smsnumber {
        get {
            return this.smsnumberField;
        }
        set {
            this.smsnumberField = value;
        }
    }

    /// <remarks/>
    public string emailaddress
    {
        get
        {
            return this.emailaddressField;
        }
        set
        {
            this.emailaddressField = value;
        }
    }
    
    /// <remarks/>
    public string ptzurlbase
    {
        get
        {
            return this.ptzurlbaseField;
        }
        set
        {
            this.ptzurlbaseField = value;
        }
    }

    /// <remarks/>
    public bool ptzautotrack
    {
        get
        {
            return this.ptzautotrackField;
        }
        set
        {
            this.ptzautotrackField = value;
        }
    }

    /// <remarks/>
    public bool ptzautotrackreverse
    {
        get
        {
            return this.ptzautotrackreverseField;
        }
        set
        {
            this.ptzautotrackreverseField = value;
        }
    }

    public string ptzchannel
    {
        get { return this.ptzchannelField; }
        set { this.ptzchannelField = value; }
    }

     /// <remarks/>
    public int ptztimetohome
    {
        get
        {
            return this.ptztimetohomeField;
        }
        set
        {
            this.ptztimetohomeField = value;
        }
    }
    
    /// <remarks/>
    public bool ptzautohome
    {
        get
        {
            return this.ptzautohomeField;
        }
        set
        {
            this.ptzautohomeField = value;
        }
    }

    /// <remarks/>
    public string ptzautohomecommand
    {
        get {
            return this.ptzautohomecommandField;
        }
        set {
            this.ptzautohomecommandField = value;
        }
    }
    
    /// <remarks/>
    public string ffmpeg {
        get {
            return this.ffmpegField;
        }
        set {
            this.ffmpegField = value;
        }
    }
    
    /// <remarks/>
    public bool deleteavi {
        get {
            return this.deleteaviField;
        }
        set {
            this.deleteaviField = value;
        }
    }
    
    /// <remarks/>
    public int micpair {
        get {
            return this.micpairField;
        }
        set {
            this.micpairField = value;
        }
    }

    /// <remarks/>
    public string maskimage
    {
        get
        {
            return this.maskimageField;
        }
        set
        {
            this.maskimageField = value;
        }
    }

    /// <remarks/>
    public string vlcargs
    {
        get
        {
            return this.vlcargsField;
        }
        set
        {
            this.vlcargsField = value;
        }
    }
    
    /// <remarks/>
    public string timestampformatter {
        get {
            return this.timestampformatterField;
        }
        set {
            this.timestampformatterField = value;
        }
    }
    
    /// <remarks/>
    public int timestamplocation {
        get {
            return this.timestamplocationField;
        }
        set {
            this.timestamplocationField = value;
        }
    }

    /// <remarks/>
    public int timestampfontsize
    {
        get {
            return this.timestampfontsizeField;
        }
        set {
            this.timestampfontsizeField = value;
        }
    }

    
    
    /// <remarks/>
    public objectsCameraSettingsYoutube youtube {
        get {
            return this.youtubeField;
        }
        set {
            this.youtubeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool resize
    {
        get
        {
            return this.resizeField;
        }
        set
        {
            this.resizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool desktopmouse
    {
        get
        {
            return this.desktopmouseField;
        }
        set
        {
            this.desktopmouseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int desktopresizewidth
    {
        get
        {
            return this.desktopresizewidthField;
        }
        set
        {
            this.desktopresizewidthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int desktopresizeheight
    {
        get
        {
            return this.desktopresizeheightField;
        }
        set
        {
            this.desktopresizeheightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string desktoparea
    {
        get
        {
            return this.desktopareaField;
        }
        set
        {
            this.desktopareaField = value;
        }
    }

    
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraSettingsYoutube {
    
    private bool autouploadField;
    
    private bool publicField;
    
    private string tagsField;
    
    private string categoryField;
    
    /// <remarks/>
    public bool autoupload {
        get {
            return this.autouploadField;
        }
        set {
            this.autouploadField = value;
        }
    }
    
    /// <remarks/>
    public bool @public {
        get {
            return this.publicField;
        }
        set {
            this.publicField = value;
        }
    }
    
    /// <remarks/>
    public string tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraFtp {
    
    private bool enabledField;
    
    private string serverField;
    
    private string usernameField;
    
    private string passwordField;
    
    private string filenameField;
    
    private int portField;
    
    private int intervalField;

    private int counterField;

    private int countermaxField;

    private int modeField;
    
    private bool readyField;

    private bool usepassiveField;

    private string textField;

    private bool savelocalField;

    private int qualityField;

    private string localfilenameField;

    /// <remarks/>
    public string localfilename
    {
        get
        {
            return this.localfilenameField;
        }
        set
        {
            this.localfilenameField = value;
        }
    }

    /// <remarks/>
    public int quality
    {
        get
        {
            return this.qualityField;
        }
        set
        {
            this.qualityField = value;
        }
    }

    public bool savelocal
    {
        get
        {
            return this.savelocalField;
        }
        set
        {
            this.savelocalField = value;
        }
    }
    /// <remarks/>
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    public string server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public string text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }
    
    /// <remarks/>
    public int port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    public int interval {
        get {
            return this.intervalField;
        }
        set {
            this.intervalField = value;
        }
    }

    /// <remarks/>
    public int counter
    {
        get
        {
            return this.counterField;
        }
        set
        {
            this.counterField = value;
        }
    }

    /// <remarks/>
    public int countermax
    {
        get
        {
            return this.countermaxField;
        }
        set
        {
            this.countermaxField = value;
        }
    }

    /// <remarks/>
    public int mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    public bool ready {
        get {
            return this.readyField;
        }
        set {
            this.readyField = value;
        }
    }

    /// <remarks/>
    public bool usepassive {
        get {
            return this.usepassiveField;
        }
        set {
            this.usepassiveField = value;
        }
    }

    
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraDetector {
    
    private objectsCameraDetectorZone[] motionzonesField;
    
    private string typeField;
    
    private string postprocessorField;
    
    private int nomovementintervalField;
    
    private int movementintervalField;
    
    private int calibrationdelayField;
    
    private double sensitivityField;

    private double maxsensitivityField;

    private double minsensitivityField;
    
    private string colorField;
    
    private bool keepobjectedgesField;
    
    private bool recordondetectField;

    private bool recordonalertField;
    
    private int processeveryframeField;

    private int minwidthField;

    private int minheightField;

    private bool highlightField;

    private string colourprocessingField;

    /// <remarks/>
    public string colourprocessing
    {
        get
        {
            return this.colourprocessingField;
        }
        set
        {
            this.colourprocessingField = value;
        }
    }

    private bool colourprocessingenabledField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool colourprocessingenabled
    {
        get
        {
            return this.colourprocessingenabledField;
        }
        set
        {
            this.colourprocessingenabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("zone", IsNullable=false)]
    public objectsCameraDetectorZone[] motionzones {
        get {
            return this.motionzonesField;
        }
        set {
            this.motionzonesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string postprocessor {
        get {
            return this.postprocessorField;
        }
        set {
            this.postprocessorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int nomovementinterval {
        get {
            return this.nomovementintervalField;
        }
        set {
            this.nomovementintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int movementinterval {
        get {
            return this.movementintervalField;
        }
        set {
            this.movementintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int calibrationdelay {
        get {
            return this.calibrationdelayField;
        }
        set {
            this.calibrationdelayField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minwidth
    {
        get
        {
            return this.minwidthField;
        }
        set
        {
            this.minwidthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minheight
    {
        get
        {
            return this.minheightField;
        }
        set
        {
            this.minheightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double sensitivity {
        get {
            return this.sensitivityField;
        }
        set {
            this.sensitivityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double maxsensitivity
    {
        get {
            return this.maxsensitivityField;
        }
        set {
            this.maxsensitivityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double minsensitivity
    {
        get {
            return this.minsensitivityField;
        }
        set {
            this.minsensitivityField = value;
        }
    }

    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool keepobjectedges {
        get {
            return this.keepobjectedgesField;
        }
        set {
            this.keepobjectedgesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordondetect {
        get {
            return this.recordondetectField;
        }
        set {
            this.recordondetectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool highlight
    {
        get
        {
            return this.highlightField;
        }
        set
        {
            this.highlightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonalert
    {
        get
        {
            return this.recordonalertField;
        }
        set
        {
            this.recordonalertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int processeveryframe {
        get {
            return this.processeveryframeField;
        }
        set {
            this.processeveryframeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraDetectorZone {
    
    private int leftField;
    
    private int topField;
    
    private int widthField;
    
    private int heightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int left {
        get {
            return this.leftField;
        }
        set {
            this.leftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int top {
        get {
            return this.topField;
        }
        set {
            this.topField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraRecorder {
    
    private int bufferframesField;

    private int buffersecondsField;
    
    private int inactiverecordField;
    
    private int maxrecordtimeField;
    
    private int timelapseField;
    
    private int timelapseframesField;

    private bool timelapseenabledField;

    private int timelapsesaveField;

    private int timelapseframerateField;

    private int qualityField;

    private int profileField;

    private bool crfField;

    private string triggerField;


    public string trigger
    {
        get { return this.triggerField; }
        set { this.triggerField = value; }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int profile
    {
        get
        {
            return this.profileField;
        }
        set
        {
            this.profileField = value;
        }
    }

        
        /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int timelapsesave
    {
        get
        {
            return this.timelapsesaveField;
        }
        set
        {
            this.timelapsesaveField = value;
        }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int timelapseframerate
    {
        get
        {
            return this.timelapseframerateField;
        }
        set
        {
            this.timelapseframerateField = value;
        }
    }

    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int quality
    {
        get
        {
            return this.qualityField;
        }
        set
        {
            this.qualityField = value;
        }
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int bufferseconds
    {
        get
        {
            return this.buffersecondsField;
        }
        set
        {
            this.buffersecondsField = value;
        }
    }
    
    /// <remarks>obsolete - use buffer seconds instead</remarks>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int bufferframes {
        get {
            return this.bufferframesField;
        }
        set {
            this.bufferframesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int inactiverecord {
        get {
            return this.inactiverecordField;
        }
        set {
            this.inactiverecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maxrecordtime {
        get {
            return this.maxrecordtimeField;
        }
        set {
            this.maxrecordtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int timelapse {
        get {
            return this.timelapseField;
        }
        set {
            this.timelapseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int timelapseframes {
        get {
            return this.timelapseframesField;
        }
        set {
            this.timelapseframesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool timelapseenabled
    {
        get
        {
            return this.timelapseenabledField;
        }
        set
        {
            this.timelapseenabledField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool crf
    {
        get
        {
            return this.crfField;
        }
        set
        {
            this.crfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraAlerts {
    
    private string alertoptionsField;
    
    private string executefileField;

    private string argumentsField;
    
    private int minimumintervalField;
    
    private int objectcountalertField;
    
    private bool activeField;
    
    private string modeField;

    private string numberplatesField;

    private int numberplatesmodeField;

    private int numberplatesintervalField;

    private bool overlayField;

    private int numberplatesaccuracyField;

    private string numberplatesareaField;

    private string pluginconfigField;

    private string processmodeField;

    private bool maximiseField;

    private string triggerField;

    private string playsoundField;

    public string playsound
    {
        get { return this.playsoundField; }
        set { this.playsoundField = value; }
    }
    
    public string trigger
    {
        get { return this.triggerField; }
        set { this.triggerField = value; }
    }


    public bool maximise
    {
        get
        {
            return this.maximiseField;
        }
        set
        {
            this.maximiseField = value;
        }
    }
    /// <remarks/>
    public string processmode
    {
        get
        {
            return this.processmodeField;
        }
        set
        {
            this.processmodeField = value;
        }
    }
    
    /// <remarks/>
    public string pluginconfig
    {
        get
        {
            return this.pluginconfigField;
        }
        set
        {
            this.pluginconfigField = value;
        }
    }
    

    /// <remarks/>
    public string alertoptions {
        get {
            return this.alertoptionsField;
        }
        set {
            this.alertoptionsField = value;
        }
    }
    
    /// <remarks/>
    public string executefile {
        get {
            return this.executefileField;
        }
        set {
            this.executefileField = value;
        }
    }

    /// <remarks/>
    public string arguments
    {
        get
        {
            return this.argumentsField;
        }
        set
        {
            this.argumentsField = value;
        }
    }

   

    /// <remarks/>
    public string numberplatesarea
    {
        get
        {
            return this.numberplatesareaField;
        }
        set
        {
            this.numberplatesareaField = value;
        }
    }

    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minimuminterval {
        get {
            return this.minimumintervalField;
        }
        set {
            this.minimumintervalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numberplatesaccuracy
    {
        get
        {
            return this.numberplatesaccuracyField;
        }
        set
        {
            this.numberplatesaccuracyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numberplatesmode
    {
        get
        {
            return this.numberplatesmodeField;
        }
        set
        {
            this.numberplatesmodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numberplatesinterval
    {
        get
        {
            return this.numberplatesintervalField;
        }
        set
        {
            this.numberplatesintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int objectcountalert {
        get {
            return this.objectcountalertField;
        }
        set {
            this.objectcountalertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool overlay
    {
        get
        {
            return this.overlayField;
        }
        set
        {
            this.overlayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numberplates
    {
        get
        {
            return this.numberplatesField;
        }
        set
        {
            this.numberplatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraNotifications {
    
    private int emailgrabintervalField;
    
    private bool sendemailField;
    
    private bool sendsmsField;
    
    private bool sendmmsField;

    private bool sendtwitterField;
        
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendtwitter
    {
        get
        {
            return this.sendtwitterField;
        }
        set
        {
            this.sendtwitterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int emailgrabinterval {
        get {
            return this.emailgrabintervalField;
        }
        set {
            this.emailgrabintervalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendemail {
        get {
            return this.sendemailField;
        }
        set {
            this.sendemailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendsms {
        get {
            return this.sendsmsField;
        }
        set {
            this.sendsmsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendmms {
        get {
            return this.sendmmsField;
        }
        set {
            this.sendmmsField = value;
        }
    }
 }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraSchedule {
    
    private objectsCameraScheduleEntry[] entriesField;
    
    private bool activeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
    public objectsCameraScheduleEntry[] entries {
        get {
            return this.entriesField;
        }
        set {
            this.entriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraScheduleEntry {
    
    private string startField;
    
    private string stopField;
    
    private string daysofweekField;

    private bool recordonstartField;

    private bool activeField;

    private bool recordondetectField;

    private bool recordonalertField;

    private bool alertsField;

    private bool timelapseenabledField;

    private bool ftpenabledField;

    private bool savelocalenabledField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ftpenabled
    {
        get
        {
            return this.ftpenabledField;
        }
        set
        {
            this.ftpenabledField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool savelocalenabled
    {
        get
        {
            return this.savelocalenabledField;
        }
        set
        {
            this.savelocalenabledField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stop {
        get {
            return this.stopField;
        }
        set {
            this.stopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string daysofweek {
        get {
            return this.daysofweekField;
        }
        set {
            this.daysofweekField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonstart
    {
        get
        {
            return this.recordonstartField;
        }
        set
        {
            this.recordonstartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordondetect
    {
        get
        {
            return this.recordondetectField;
        }
        set
        {
            this.recordondetectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonalert
    {
        get
        {
            return this.recordonalertField;
        }
        set
        {
            this.recordonalertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool alerts
    {
        get
        {
            return this.alertsField;
        }
        set
        {
            this.alertsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool timelapseenabled
    {
        get
        {
            return this.timelapseenabledField;
        }
        set
        {
            this.timelapseenabledField = value;
        }
    }

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophone {
    
    private objectsMicrophoneSettings settingsField;
    
    private objectsMicrophoneDetector detectorField;
    
    private objectsMicrophoneRecorder recorderField;
    
    private objectsMicrophoneAlerts alertsField;
    
    private objectsMicrophoneNotifications notificationsField;
    
    private objectsMicrophoneSchedule scheduleField;
    
    private int idField;
    
    private string nameField;

    private string directoryField;
    
    private string descriptionField;
    
    private int xField;
    
    private int yField;
    
    private int widthField;
    
    private int heightField;

    private int newrecordingcountField;
    
    /// <remarks/>
    public objectsMicrophoneSettings settings {
        get {
            return this.settingsField;
        }
        set {
            this.settingsField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneDetector detector {
        get {
            return this.detectorField;
        }
        set {
            this.detectorField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneRecorder recorder {
        get {
            return this.recorderField;
        }
        set {
            this.recorderField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneAlerts alerts {
        get {
            return this.alertsField;
        }
        set {
            this.alertsField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneNotifications notifications {
        get {
            return this.notificationsField;
        }
        set {
            this.notificationsField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneSchedule schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string directory
    {
        get
        {
            return this.directoryField;
        }
        set
        {
            this.directoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int newrecordingcount
    {
        get
        {
            return this.newrecordingcountField;
        }
        set
        {
            this.newrecordingcountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneSettings {
    
    private int sourceindexField;
    
    private int bufferField;
    
    private int samplesField;
    
    private int bitsField;
    
    private int channelsField;
    
    private bool activeField;

    private bool needsupdateField;
    
    private string smsnumberField;
    
    private string emailaddressField;
    
    private string sourcenameField;

    private string deviceoutField;

    private string usernameField;

    private string passwordField;

    private int typeindexField;
    
    private string ffmpegField;
    
    private bool deletewavField;
    
    private bool decompressField;

    private bool notifyondisconnectField;

    private string vlcargsField;

    private int volumeField;

    private int reconnectintervalField;

    private string accessgroupsField;

    private float gainField;

    /// <remarks/>
    public string accessgroups
    {
        get
        {
            return this.accessgroupsField;
        }
        set
        {
            this.accessgroupsField = value;
        }
    }

    /// <remarks/>
    public int reconnectinterval
    {
        get
        {
            return this.reconnectintervalField;
        }
        set
        {
            this.reconnectintervalField = value;
        }
    }
    
    /// <remarks/>
    public int sourceindex {
        get {
            return this.sourceindexField;
        }
        set {
            this.sourceindexField = value;
        }
    }

    /// <remarks/>
    public int buffer {
        get {
            return this.bufferField;
        }
        set {
            this.bufferField = value;
        }
    }
    
    /// <remarks/>
    public int samples {
        get {
            return this.samplesField;
        }
        set {
            this.samplesField = value;
        }
    }
    
    /// <remarks/>
    public int bits {
        get {
            return this.bitsField;
        }
        set {
            this.bitsField = value;
        }
    }
    
    /// <remarks/>
    public int channels {
        get {
            return this.channelsField;
        }
        set {
            this.channelsField = value;
        }
    }

    /// <remarks/>
    public int volume
    {
        get
        {
            return this.volumeField;
        }
        set
        {
            this.volumeField = value;
        }
    }

    /// <remarks/>
    public float gain
    {
        get
        {
            return this.gainField;
        }
        set
        {
            this.gainField = value;
        }
    }
    
    /// <remarks/>
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }

    /// <remarks/>
    public bool needsupdate
    {
        get
        {
            return this.needsupdateField;
        }
        set
        {
            this.needsupdateField = value;
        }
    }

    /// <remarks/>
    public bool notifyondisconnect
    {
        get
        {
            return this.notifyondisconnectField;
        }
        set
        {
            this.notifyondisconnectField = value;
        }
    }
    
    /// <remarks/>
    public string smsnumber {
        get {
            return this.smsnumberField;
        }
        set {
            this.smsnumberField = value;
        }
    }

    /// <remarks/>
    public string deviceout
    {
        get
        {
            return this.deviceoutField;
        }
        set
        {
            this.deviceoutField = value;
        }
    }
    
    /// <remarks/>
    public string emailaddress {
        get {
            return this.emailaddressField;
        }
        set {
            this.emailaddressField = value;
        }
    }
    
    /// <remarks/>
    public string sourcename {
        get {
            return this.sourcenameField;
        }
        set {
            this.sourcenameField = value;
        }
    }

    /// <remarks/>
    public string vlcargs
    {
        get
        {
            return this.vlcargsField;
        }
        set
        {
            this.vlcargsField = value;
        }
    }

    /// <remarks/>
    public string username
    {
        get
        {
            return this.usernameField;
        }
        set
        {
            this.usernameField = value;
        }
    }

    /// <remarks/>
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public int typeindex
    {
        get {
            return this.typeindexField;
        }
        set {
            this.typeindexField = value;
        }
    }
    
    /// <remarks/>
    public string ffmpeg {
        get {
            return this.ffmpegField;
        }
        set {
            this.ffmpegField = value;
        }
    }
    
    /// <remarks/>
    public bool deletewav {
        get {
            return this.deletewavField;
        }
        set {
            this.deletewavField = value;
        }
    }
    
    /// <remarks/>
    public bool decompress {
        get {
            return this.decompressField;
        }
        set {
            this.decompressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneDetector {
    
    private int sensitivityField;
    
    private int nosoundintervalField;
    
    private int soundintervalField;
    
    private bool recordondetectField;

    private bool recordonalertField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sensitivity {
        get {
            return this.sensitivityField;
        }
        set {
            this.sensitivityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int nosoundinterval {
        get {
            return this.nosoundintervalField;
        }
        set {
            this.nosoundintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int soundinterval {
        get {
            return this.soundintervalField;
        }
        set {
            this.soundintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordondetect {
        get {
            return this.recordondetectField;
        }
        set {
            this.recordondetectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonalert
    {
        get
        {
            return this.recordonalertField;
        }
        set
        {
            this.recordonalertField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneRecorder {
    
    private int inactiverecordField;
    
    private int maxrecordtimeField;

    private string triggerField;


    public string trigger
    {
        get { return this.triggerField; }
        set { this.triggerField = value; }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int inactiverecord {
        get {
            return this.inactiverecordField;
        }
        set {
            this.inactiverecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maxrecordtime {
        get {
            return this.maxrecordtimeField;
        }
        set {
            this.maxrecordtimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneAlerts {
    
    private string alertoptionsField;
    
    private string executefileField;
    
    private int minimumintervalField;
    
    private bool activeField;
    
    private string modeField;

    private string argumentsField;

    private string triggerField;


    public string trigger
    {
        get { return this.triggerField; }
        set { this.triggerField = value; }
    }

    /// <remarks/>
    public string arguments
    {
        get
        {
            return this.argumentsField;
        }
        set
        {
            this.argumentsField = value;
        }
    }
    
    /// <remarks/>
    public string alertoptions {
        get {
            return this.alertoptionsField;
        }
        set {
            this.alertoptionsField = value;
        }
    }
    
    /// <remarks/>
    public string executefile {
        get {
            return this.executefileField;
        }
        set {
            this.executefileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minimuminterval {
        get {
            return this.minimumintervalField;
        }
        set {
            this.minimumintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneNotifications {
    
    private bool sendemailField;
    
    private bool sendsmsField;

    private bool sendtwitterField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendtwitter
    {
        get
        {
            return this.sendtwitterField;
        }
        set
        {
            this.sendtwitterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendemail {
        get {
            return this.sendemailField;
        }
        set {
            this.sendemailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendsms {
        get {
            return this.sendsmsField;
        }
        set {
            this.sendsmsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneSchedule {
    
    private objectsMicrophoneScheduleEntry[] entriesField;
    
    private bool activeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
    public objectsMicrophoneScheduleEntry[] entries {
        get {
            return this.entriesField;
        }
        set {
            this.entriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneScheduleEntry {
    
    private string startField;
    
    private string stopField;
    
    private string daysofweekField;

    private bool recordonstartField;

    private bool activeField;

    private bool recordondetectField;

    private bool recordonalertField;

    private bool alertsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stop {
        get {
            return this.stopField;
        }
        set {
            this.stopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string daysofweek {
        get {
            return this.daysofweekField;
        }
        set {
            this.daysofweekField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonstart
    {
        get
        {
            return this.recordonstartField;
        }
        set
        {
            this.recordonstartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordondetect
    {
        get
        {
            return this.recordondetectField;
        }
        set
        {
            this.recordondetectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonalert
    {
        get
        {
            return this.recordonalertField;
        }
        set
        {
            this.recordonalertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool alerts
    {
        get
        {
            return this.alertsField;
        }
        set
        {
            this.alertsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsFloorplan {
    
    private objectsFloorplanObjects objectsField;
    
    private int idField;
    
    private string nameField;
    
    private int xField;
    
    private int yField;
    
    private int widthField;
    
    private int heightField;
    
    private string imageField;
    
    private bool needsupdateField;

    private bool originalsizeField;
   
    /// <remarks/>
    public objectsFloorplanObjects objects {
        get {
            return this.objectsField;
        }
        set {
            this.objectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }

    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool needsupdate {
        get {
            return this.needsupdateField;
        }
        set {
            this.needsupdateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool originalsize
    {
        get
        {
            return this.originalsizeField;
        }
        set
        {
            this.originalsizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsFloorplanObjects {
    
    private objectsFloorplanObjectsEntry[] objectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
    public objectsFloorplanObjectsEntry[] @object {
        get {
            return this.objectField;
        }
        set {
            this.objectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsFloorplanObjectsEntry {
    
    private string typeField;
    
    private int idField;
    
    private int xField;
    
    private int yField;

    private int angleField;

    private int fovField;

    private int radiusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int angle
    {
        get
        {
            return this.angleField;
        }
        set
        {
            this.angleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int radius
    {
        get
        {
            return this.radiusField;
        }
        set
        {
            this.radiusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int fov
    {
        get
        {
            return this.fovField;
        }
        set
        {
            this.fovField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCommand {
    
    private int idField;
    
    private string nameField;
    
    private string commandField;

    private string smscommandField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string smscommand
    {
        get
        {
            return this.smscommandField;
        }
        set
        {
            this.smscommandField = value;
        }
    }
}
