//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class configuration {
    
    private string wSUsernameField;
    
    private string wSPasswordField;
    
    private bool servicesEnabledField;
    
    private int serverPortField;
    
    private string motion_WSActivity_iSpyField;
    
    private bool enable_Error_ReportingField;
    
    private bool enable_Update_CheckField;
    
    private string password_Protect_PasswordField;
    
    private bool enable_Password_ProtectField;
    
    private string mJPEGURLField;
    
    private string aVIFileNameField;
    
    private string recentJPGListField;
    
    private string recentMJPGListField;
    
    private string recentFileListField;
    
    private bool subscribedField;
    
    private string jPEGURLField;
    
    private string activityColorField;
    
    private string noActivityColorField;
    
    private string trackingColorField;
    
    private string floorPlanHighlightColorField;
    
    private string volumeLevelColorField;
    
    private int maxRecordingThreadsField;
    
    private string mainColorField;
    
    private string areaColorField;
    
    private string backColorField;
    
    private int maxMediaFolderSizeMBField;
    
    private int deleteFilesOlderThanDaysField;
    
    private string serverAddressField;
    
    private bool enabled_ShowGettingStartedField;
    
    private int opacityField;
    
    private int lANPortField;
    
    private bool enable_Storage_ManagementField;
    
    private string fFMPEG_CameraField;
    
    private string fFMPEG_MicrophoneField;
    
    private string timestampColorField;
    
    private string borderHighlightColorField;
    
    private string borderDefaultColorField;
    
    private bool useUPNPField;
    
    private string youTubeUsernameField;
    
    private string youTubePasswordField;
    
    private string youTubeAccountField;
    
    private string youTubeKeyField;
    
    private string youTubeCategoriesField;
    
    private string youTubeDefaultCategoryField;
    
    private string compressorOptionsField;
    
    private bool logFFMPEGCommandsField;
    
    private bool balloonTipsField;
    
    private string trayIconTextField;
    
    private bool autoLayoutField;
    
    private string upnpDeviceField;
    
    private string iPModeField;
    
    private string iPv4AddressField;
    
    private string iPv6AddressField;
    
    private bool dHCPRerouteField;
    
    private string mediaDirectoryField;
    
    private bool fFMPEG_SingleProcessField;
    
    private bool loopbackField;
    
    private int serverReceiveTimeoutField;
    
    private int iPCameraTimeoutField;
    
    private string serverNameField;
    
    private string uploadedVideosField;
    
    private string languageField;
    
    private string recentVLCListField;
    
    private string vLCURLField;
    
    private bool autoScheduleField;
    
    private bool fullscreenField;
    
    private bool showStatusField;
    
    private bool showToolbarField;
    
    private bool showFileMenuField;
    
    private bool alwaysOnTopField;
    
    private int logFileSizeKBField;
    
    private int cPUMaxField;
    
    private string allowedIPListField;
    
    private string resellerField;
    
    private bool createAlertWindowsField;
    
    private int maxRedrawRateField;
    
    private int previewItemsField;
    
    private bool showOverlayControlsField;
    
    private bool showMediaPanelField;
    
    private int priorityField;
    
    private bool monitorField;
    
    private int runTimesField;
    
    private bool screensaverWakeupField;
    
    private string vendorField;
    
    private string talkMicField;
    
    private int playbackModeField;
    
    private int jPEGQualityField;
    
    private bool stopSavingOnStorageLimitField;
    
    private bool viewControllerField;
    
    private int layoutModeField;
    
    private bool showPTZControllerField;
    
    private bool bigButtonsField;
    
    private bool lockLayoutField;
    
    private string mediaPanelSizeField;
       
    private bool minimiseOnCloseField;
    
    private bool iPv6DisabledField;
    
    private bool deleteToRecycleBinField;
    
    private bool speechRecognitionField;
    
    private string defaultManufacturerField;
    
    private string appendLinkTextField;

    private string startupFormField;

    private bool trayOnMinimiseField;
    
    private configurationGrid[] gridViewsField;
    
    private configurationJoystick joystickField;

    private int featureSetField;

    private int MJPEGStreamIntervalField;
    
    public configuration() {
        this.maxRecordingThreadsField = 4;
        this.cPUMaxField = 90;
        this.allowedIPListField = "";
        this.resellerField = "";
        this.createAlertWindowsField = true;
        this.maxRedrawRateField = 10;
        this.previewItemsField = 100;
        this.showOverlayControlsField = true;
        this.showMediaPanelField = true;
        this.priorityField = 3;
        this.monitorField = true;
        this.runTimesField = 0;
        this.screensaverWakeupField = false;
        this.vendorField = "";
        this.talkMicField = "";
        this.playbackModeField = 0;
        this.jPEGQualityField = 75;
        this.stopSavingOnStorageLimitField = false;
        this.viewControllerField = true;
        this.layoutModeField = 0;
        this.showPTZControllerField = false;
        this.bigButtonsField = false;
        this.lockLayoutField = false;
        this.mediaPanelSizeField = "";
        this.minimiseOnCloseField = false;
        this.iPv6DisabledField = false;
        this.deleteToRecycleBinField = false;
        this.speechRecognitionField = false;
        this.appendLinkTextField = "http://www.ispyconnect.com/watch_new.aspx";
        this.startupFormField = "iSpy";
        this.trayOnMinimiseField = true;
        this.featureSetField = -1;
        this.MJPEGStreamIntervalField = 100;
    }


    /// <remarks/>
    public int MJPEGStreamInterval
    {
        get
        {
            return this.MJPEGStreamIntervalField;
        }
        set
        {
            this.MJPEGStreamIntervalField = value;
        }
    }
    
    /// <remarks/>
    public bool TrayOnMinimise
    {
        get {
            return this.trayOnMinimiseField;
        }
        set {
            this.trayOnMinimiseField = value;
        }
    }
        
        /// <remarks/>
    public string WSUsername {
        get {
            return this.wSUsernameField;
        }
        set {
            this.wSUsernameField = value;
        }
    }
    
    /// <remarks/>
    public string WSPassword {
        get {
            return this.wSPasswordField;
        }
        set {
            this.wSPasswordField = value;
        }
    }
    
    /// <remarks/>
    public bool ServicesEnabled {
        get {
            return this.servicesEnabledField;
        }
        set {
            this.servicesEnabledField = value;
        }
    }
    
    /// <remarks/>
    public int ServerPort {
        get {
            return this.serverPortField;
        }
        set {
            this.serverPortField = value;
        }
    }

    /// <remarks/>
    public int FeatureSet
    {
        get
        {
            return this.featureSetField;
        }
        set
        {
            this.featureSetField = value;
        }
    }
    
    /// <remarks/>
    public string motion_WSActivity_iSpy {
        get {
            return this.motion_WSActivity_iSpyField;
        }
        set {
            this.motion_WSActivity_iSpyField = value;
        }
    }
    
    /// <remarks/>
    public bool Enable_Error_Reporting {
        get {
            return this.enable_Error_ReportingField;
        }
        set {
            this.enable_Error_ReportingField = value;
        }
    }
    
    /// <remarks/>
    public bool Enable_Update_Check {
        get {
            return this.enable_Update_CheckField;
        }
        set {
            this.enable_Update_CheckField = value;
        }
    }
    
    /// <remarks/>
    public string Password_Protect_Password {
        get {
            return this.password_Protect_PasswordField;
        }
        set {
            this.password_Protect_PasswordField = value;
        }
    }
    
    /// <remarks/>
    public bool Enable_Password_Protect {
        get {
            return this.enable_Password_ProtectField;
        }
        set {
            this.enable_Password_ProtectField = value;
        }
    }
    
    /// <remarks/>
    public string MJPEGURL {
        get {
            return this.mJPEGURLField;
        }
        set {
            this.mJPEGURLField = value;
        }
    }
    
    /// <remarks/>
    public string AVIFileName {
        get {
            return this.aVIFileNameField;
        }
        set {
            this.aVIFileNameField = value;
        }
    }
    
    /// <remarks/>
    public string RecentJPGList {
        get {
            return this.recentJPGListField;
        }
        set {
            this.recentJPGListField = value;
        }
    }
    
    /// <remarks/>
    public string RecentMJPGList {
        get {
            return this.recentMJPGListField;
        }
        set {
            this.recentMJPGListField = value;
        }
    }
    
    /// <remarks/>
    public string RecentFileList {
        get {
            return this.recentFileListField;
        }
        set {
            this.recentFileListField = value;
        }
    }
    
    /// <remarks/>
    public bool Subscribed {
        get {
            return this.subscribedField;
        }
        set {
            this.subscribedField = value;
        }
    }
    
    /// <remarks/>
    public string JPEGURL {
        get {
            return this.jPEGURLField;
        }
        set {
            this.jPEGURLField = value;
        }
    }
    
    /// <remarks/>
    public string ActivityColor {
        get {
            return this.activityColorField;
        }
        set {
            this.activityColorField = value;
        }
    }
    
    /// <remarks/>
    public string NoActivityColor {
        get {
            return this.noActivityColorField;
        }
        set {
            this.noActivityColorField = value;
        }
    }
    
    /// <remarks/>
    public string TrackingColor {
        get {
            return this.trackingColorField;
        }
        set {
            this.trackingColorField = value;
        }
    }
    
    /// <remarks/>
    public string FloorPlanHighlightColor {
        get {
            return this.floorPlanHighlightColorField;
        }
        set {
            this.floorPlanHighlightColorField = value;
        }
    }
    
    /// <remarks/>
    public string VolumeLevelColor {
        get {
            return this.volumeLevelColorField;
        }
        set {
            this.volumeLevelColorField = value;
        }
    }
    
    /// <remarks/>
    public int MaxRecordingThreads {
        get {
            return this.maxRecordingThreadsField;
        }
        set {
            this.maxRecordingThreadsField = value;
        }
    }
    
    /// <remarks/>
    public string MainColor {
        get {
            return this.mainColorField;
        }
        set {
            this.mainColorField = value;
        }
    }
    
    /// <remarks/>
    public string AreaColor {
        get {
            return this.areaColorField;
        }
        set {
            this.areaColorField = value;
        }
    }
    
    /// <remarks/>
    public string BackColor {
        get {
            return this.backColorField;
        }
        set {
            this.backColorField = value;
        }
    }
    
    /// <remarks/>
    public int MaxMediaFolderSizeMB {
        get {
            return this.maxMediaFolderSizeMBField;
        }
        set {
            this.maxMediaFolderSizeMBField = value;
        }
    }
    
    /// <remarks/>
    public int DeleteFilesOlderThanDays {
        get {
            return this.deleteFilesOlderThanDaysField;
        }
        set {
            this.deleteFilesOlderThanDaysField = value;
        }
    }
    
    /// <remarks/>
    public string ServerAddress {
        get {
            return this.serverAddressField;
        }
        set {
            this.serverAddressField = value;
        }
    }
    
    /// <remarks/>
    public bool Enabled_ShowGettingStarted {
        get {
            return this.enabled_ShowGettingStartedField;
        }
        set {
            this.enabled_ShowGettingStartedField = value;
        }
    }
    
    /// <remarks/>
    public int Opacity {
        get {
            return this.opacityField;
        }
        set {
            this.opacityField = value;
        }
    }
    
    /// <remarks/>
    public int LANPort {
        get {
            return this.lANPortField;
        }
        set {
            this.lANPortField = value;
        }
    }
    
    /// <remarks/>
    public bool Enable_Storage_Management {
        get {
            return this.enable_Storage_ManagementField;
        }
        set {
            this.enable_Storage_ManagementField = value;
        }
    }
    
    /// <remarks/>
    public string FFMPEG_Camera {
        get {
            return this.fFMPEG_CameraField;
        }
        set {
            this.fFMPEG_CameraField = value;
        }
    }
    
    /// <remarks/>
    public string FFMPEG_Microphone {
        get {
            return this.fFMPEG_MicrophoneField;
        }
        set {
            this.fFMPEG_MicrophoneField = value;
        }
    }
    
    /// <remarks/>
    public string TimestampColor {
        get {
            return this.timestampColorField;
        }
        set {
            this.timestampColorField = value;
        }
    }
    
    /// <remarks/>
    public string BorderHighlightColor {
        get {
            return this.borderHighlightColorField;
        }
        set {
            this.borderHighlightColorField = value;
        }
    }
    
    /// <remarks/>
    public string BorderDefaultColor {
        get {
            return this.borderDefaultColorField;
        }
        set {
            this.borderDefaultColorField = value;
        }
    }
    
    /// <remarks/>
    public bool UseUPNP {
        get {
            return this.useUPNPField;
        }
        set {
            this.useUPNPField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeUsername {
        get {
            return this.youTubeUsernameField;
        }
        set {
            this.youTubeUsernameField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubePassword {
        get {
            return this.youTubePasswordField;
        }
        set {
            this.youTubePasswordField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeAccount {
        get {
            return this.youTubeAccountField;
        }
        set {
            this.youTubeAccountField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeKey {
        get {
            return this.youTubeKeyField;
        }
        set {
            this.youTubeKeyField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeCategories {
        get {
            return this.youTubeCategoriesField;
        }
        set {
            this.youTubeCategoriesField = value;
        }
    }
    
    /// <remarks/>
    public string YouTubeDefaultCategory {
        get {
            return this.youTubeDefaultCategoryField;
        }
        set {
            this.youTubeDefaultCategoryField = value;
        }
    }
    
    /// <remarks/>
    public string CompressorOptions {
        get {
            return this.compressorOptionsField;
        }
        set {
            this.compressorOptionsField = value;
        }
    }
    
    /// <remarks/>
    public bool LogFFMPEGCommands {
        get {
            return this.logFFMPEGCommandsField;
        }
        set {
            this.logFFMPEGCommandsField = value;
        }
    }
    
    /// <remarks/>
    public bool BalloonTips {
        get {
            return this.balloonTipsField;
        }
        set {
            this.balloonTipsField = value;
        }
    }
    
    /// <remarks/>
    public string TrayIconText {
        get {
            return this.trayIconTextField;
        }
        set {
            this.trayIconTextField = value;
        }
    }
    
    /// <remarks/>
    public bool AutoLayout {
        get {
            return this.autoLayoutField;
        }
        set {
            this.autoLayoutField = value;
        }
    }
    
    /// <remarks/>
    public string UpnpDevice {
        get {
            return this.upnpDeviceField;
        }
        set {
            this.upnpDeviceField = value;
        }
    }
    
    /// <remarks/>
    public string IPMode {
        get {
            return this.iPModeField;
        }
        set {
            this.iPModeField = value;
        }
    }
    
    /// <remarks/>
    public string IPv4Address {
        get {
            return this.iPv4AddressField;
        }
        set {
            this.iPv4AddressField = value;
        }
    }
    
    /// <remarks/>
    public string IPv6Address {
        get {
            return this.iPv6AddressField;
        }
        set {
            this.iPv6AddressField = value;
        }
    }
    
    /// <remarks/>
    public bool DHCPReroute {
        get {
            return this.dHCPRerouteField;
        }
        set {
            this.dHCPRerouteField = value;
        }
    }
    
    /// <remarks/>
    public string MediaDirectory {
        get {
            return this.mediaDirectoryField;
        }
        set {
            this.mediaDirectoryField = value;
        }
    }
    
    /// <remarks/>
    public bool FFMPEG_SingleProcess {
        get {
            return this.fFMPEG_SingleProcessField;
        }
        set {
            this.fFMPEG_SingleProcessField = value;
        }
    }
    
    /// <remarks/>
    public bool Loopback {
        get {
            return this.loopbackField;
        }
        set {
            this.loopbackField = value;
        }
    }
    
    /// <remarks/>
    public int ServerReceiveTimeout {
        get {
            return this.serverReceiveTimeoutField;
        }
        set {
            this.serverReceiveTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public int IPCameraTimeout {
        get {
            return this.iPCameraTimeoutField;
        }
        set {
            this.iPCameraTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public string ServerName {
        get {
            return this.serverNameField;
        }
        set {
            this.serverNameField = value;
        }
    }
    
    /// <remarks/>
    public string UploadedVideos {
        get {
            return this.uploadedVideosField;
        }
        set {
            this.uploadedVideosField = value;
        }
    }
    
    /// <remarks/>
    public string Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    public string RecentVLCList {
        get {
            return this.recentVLCListField;
        }
        set {
            this.recentVLCListField = value;
        }
    }
    
    /// <remarks/>
    public string VLCURL {
        get {
            return this.vLCURLField;
        }
        set {
            this.vLCURLField = value;
        }
    }
    
    /// <remarks/>
    public bool AutoSchedule {
        get {
            return this.autoScheduleField;
        }
        set {
            this.autoScheduleField = value;
        }
    }
    
    /// <remarks/>
    public bool Fullscreen {
        get {
            return this.fullscreenField;
        }
        set {
            this.fullscreenField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowStatus {
        get {
            return this.showStatusField;
        }
        set {
            this.showStatusField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowToolbar {
        get {
            return this.showToolbarField;
        }
        set {
            this.showToolbarField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowFileMenu {
        get {
            return this.showFileMenuField;
        }
        set {
            this.showFileMenuField = value;
        }
    }
    
    /// <remarks/>
    public bool AlwaysOnTop {
        get {
            return this.alwaysOnTopField;
        }
        set {
            this.alwaysOnTopField = value;
        }
    }
    
    /// <remarks/>
    public int LogFileSizeKB {
        get {
            return this.logFileSizeKBField;
        }
        set {
            this.logFileSizeKBField = value;
        }
    }
    
    /// <remarks/>
    public int CPUMax {
        get {
            return this.cPUMaxField;
        }
        set {
            this.cPUMaxField = value;
        }
    }
    
    /// <remarks/>
    public string AllowedIPList {
        get {
            return this.allowedIPListField;
        }
        set {
            this.allowedIPListField = value;
        }
    }
    
    /// <remarks/>
    public string Reseller {
        get {
            return this.resellerField;
        }
        set {
            this.resellerField = value;
        }
    }
    
    /// <remarks/>
    public bool CreateAlertWindows {
        get {
            return this.createAlertWindowsField;
        }
        set {
            this.createAlertWindowsField = value;
        }
    }
    
    /// <remarks/>
    public int MaxRedrawRate {
        get {
            return this.maxRedrawRateField;
        }
        set {
            this.maxRedrawRateField = value;
        }
    }
    
    /// <remarks/>
    public int PreviewItems {
        get {
            return this.previewItemsField;
        }
        set {
            this.previewItemsField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowOverlayControls {
        get {
            return this.showOverlayControlsField;
        }
        set {
            this.showOverlayControlsField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowMediaPanel {
        get {
            return this.showMediaPanelField;
        }
        set {
            this.showMediaPanelField = value;
        }
    }
    
    /// <remarks/>
    public int Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    public bool Monitor {
        get {
            return this.monitorField;
        }
        set {
            this.monitorField = value;
        }
    }
    
    /// <remarks/>
    public int RunTimes {
        get {
            return this.runTimesField;
        }
        set {
            this.runTimesField = value;
        }
    }
    
    /// <remarks/>
    public bool ScreensaverWakeup {
        get {
            return this.screensaverWakeupField;
        }
        set {
            this.screensaverWakeupField = value;
        }
    }
    
    /// <remarks/>
    public string Vendor {
        get {
            return this.vendorField;
        }
        set {
            this.vendorField = value;
        }
    }
    
    /// <remarks/>
    public string TalkMic {
        get {
            return this.talkMicField;
        }
        set {
            this.talkMicField = value;
        }
    }
    
    /// <remarks/>
    public int PlaybackMode {
        get {
            return this.playbackModeField;
        }
        set {
            this.playbackModeField = value;
        }
    }
    
    /// <remarks/>
    public int JPEGQuality {
        get {
            return this.jPEGQualityField;
        }
        set {
            this.jPEGQualityField = value;
        }
    }
    
    /// <remarks/>
    public bool StopSavingOnStorageLimit {
        get {
            return this.stopSavingOnStorageLimitField;
        }
        set {
            this.stopSavingOnStorageLimitField = value;
        }
    }
    
    /// <remarks/>
    public bool ViewController {
        get {
            return this.viewControllerField;
        }
        set {
            this.viewControllerField = value;
        }
    }
    
    /// <remarks/>
    public int LayoutMode {
        get {
            return this.layoutModeField;
        }
        set {
            this.layoutModeField = value;
        }
    }
    
    /// <remarks/>
    public bool ShowPTZController {
        get {
            return this.showPTZControllerField;
        }
        set {
            this.showPTZControllerField = value;
        }
    }
    
    /// <remarks/>
    public bool BigButtons {
        get {
            return this.bigButtonsField;
        }
        set {
            this.bigButtonsField = value;
        }
    }
    
    /// <remarks/>
    public bool LockLayout {
        get {
            return this.lockLayoutField;
        }
        set {
            this.lockLayoutField = value;
        }
    }
    
    /// <remarks/>
    public string MediaPanelSize {
        get {
            return this.mediaPanelSizeField;
        }
        set {
            this.mediaPanelSizeField = value;
        }
    }
       
    /// <remarks/>
    public bool MinimiseOnClose {
        get {
            return this.minimiseOnCloseField;
        }
        set {
            this.minimiseOnCloseField = value;
        }
    }
    
    /// <remarks/>
    public bool IPv6Disabled {
        get {
            return this.iPv6DisabledField;
        }
        set {
            this.iPv6DisabledField = value;
        }
    }
    
    /// <remarks/>
    public bool DeleteToRecycleBin {
        get {
            return this.deleteToRecycleBinField;
        }
        set {
            this.deleteToRecycleBinField = value;
        }
    }
    
    /// <remarks/>
    public bool SpeechRecognition {
        get {
            return this.speechRecognitionField;
        }
        set {
            this.speechRecognitionField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultManufacturer {
        get {
            return this.defaultManufacturerField;
        }
        set {
            this.defaultManufacturerField = value;
        }
    }
    
    /// <remarks/>
    public string AppendLinkText {
        get {
            return this.appendLinkTextField;
        }
        set {
            this.appendLinkTextField = value;
        }
    }

    /// <remarks/>
    public string StartupForm
    {
        get
        {
            return this.startupFormField;
        }
        set
        {
            this.startupFormField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Grid", IsNullable=false)]
    public configurationGrid[] GridViews {
        get {
            return this.gridViewsField;
        }
        set {
            this.gridViewsField = value;
        }
    }
    
    /// <remarks/>
    public configurationJoystick Joystick {
        get {
            return this.joystickField;
        }
        set {
            this.joystickField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationGrid {
    
    private configurationGridGridItem[] gridItemField;
    
    private string nameField;
    
    private int rowsField;
    
    private int columnsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GridItem")]
    public configurationGridGridItem[] GridItem {
        get {
            return this.gridItemField;
        }
        set {
            this.gridItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Rows {
        get {
            return this.rowsField;
        }
        set {
            this.rowsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Columns {
        get {
            return this.columnsField;
        }
        set {
            this.columnsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationGridGridItem {
    
    private configurationGridGridItemItem[] itemField;
    
    private int gridIndexField;
    
    private int cycleDelayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public configurationGridGridItemItem[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int GridIndex {
        get {
            return this.gridIndexField;
        }
        set {
            this.gridIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int CycleDelay {
        get {
            return this.cycleDelayField;
        }
        set {
            this.cycleDelayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationGridGridItemItem {
    
    private int typeIDField;
    
    private int objectIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TypeID {
        get {
            return this.typeIDField;
        }
        set {
            this.typeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ObjectID {
        get {
            return this.objectIDField;
        }
        set {
            this.objectIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class configurationJoystick {
    
    private string idField;
    
    private int xAxisField;
    
    private bool xAxisFieldSpecified;
    
    private int centerXAxisField;
    
    private bool centerXAxisFieldSpecified;
    
    private bool invertXAxisField;
    
    private bool invertXAxisFieldSpecified;
    
    private int yAxisField;
    
    private bool yAxisFieldSpecified;
    
    private int centerYAxisField;
    
    private bool centerYAxisFieldSpecified;
    
    private bool invertYAxisField;
    
    private bool invertYAxisFieldSpecified;
    
    private int zAxisField;
    
    private bool zAxisFieldSpecified;
    
    private int centerZAxisField;
    
    private bool centerZAxisFieldSpecified;
    
    private bool invertZAxisField;
    
    private bool invertZAxisFieldSpecified;
    
    private int recordField;
    
    private bool recordFieldSpecified;
    
    private int snapshotField;
    
    private bool snapshotFieldSpecified;
    
    private int listenField;
    
    private bool listenFieldSpecified;
    
    private int talkField;
    
    private bool talkFieldSpecified;
    
    private int playField;
    
    private bool playFieldSpecified;
    
    private int stopField;
    
    private bool stopFieldSpecified;
    
    private int nextField;
    
    private bool nextFieldSpecified;
    
    private int previousField;
    
    private bool previousFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int XAxis {
        get {
            return this.xAxisField;
        }
        set {
            this.xAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XAxisSpecified {
        get {
            return this.xAxisFieldSpecified;
        }
        set {
            this.xAxisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int CenterXAxis {
        get {
            return this.centerXAxisField;
        }
        set {
            this.centerXAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CenterXAxisSpecified {
        get {
            return this.centerXAxisFieldSpecified;
        }
        set {
            this.centerXAxisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool InvertXAxis {
        get {
            return this.invertXAxisField;
        }
        set {
            this.invertXAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvertXAxisSpecified {
        get {
            return this.invertXAxisFieldSpecified;
        }
        set {
            this.invertXAxisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int YAxis {
        get {
            return this.yAxisField;
        }
        set {
            this.yAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool YAxisSpecified {
        get {
            return this.yAxisFieldSpecified;
        }
        set {
            this.yAxisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int CenterYAxis {
        get {
            return this.centerYAxisField;
        }
        set {
            this.centerYAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CenterYAxisSpecified {
        get {
            return this.centerYAxisFieldSpecified;
        }
        set {
            this.centerYAxisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool InvertYAxis {
        get {
            return this.invertYAxisField;
        }
        set {
            this.invertYAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvertYAxisSpecified {
        get {
            return this.invertYAxisFieldSpecified;
        }
        set {
            this.invertYAxisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ZAxis {
        get {
            return this.zAxisField;
        }
        set {
            this.zAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ZAxisSpecified {
        get {
            return this.zAxisFieldSpecified;
        }
        set {
            this.zAxisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int CenterZAxis {
        get {
            return this.centerZAxisField;
        }
        set {
            this.centerZAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CenterZAxisSpecified {
        get {
            return this.centerZAxisFieldSpecified;
        }
        set {
            this.centerZAxisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool InvertZAxis {
        get {
            return this.invertZAxisField;
        }
        set {
            this.invertZAxisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvertZAxisSpecified {
        get {
            return this.invertZAxisFieldSpecified;
        }
        set {
            this.invertZAxisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Record {
        get {
            return this.recordField;
        }
        set {
            this.recordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RecordSpecified {
        get {
            return this.recordFieldSpecified;
        }
        set {
            this.recordFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Snapshot {
        get {
            return this.snapshotField;
        }
        set {
            this.snapshotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SnapshotSpecified {
        get {
            return this.snapshotFieldSpecified;
        }
        set {
            this.snapshotFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Listen {
        get {
            return this.listenField;
        }
        set {
            this.listenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ListenSpecified {
        get {
            return this.listenFieldSpecified;
        }
        set {
            this.listenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Talk {
        get {
            return this.talkField;
        }
        set {
            this.talkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TalkSpecified {
        get {
            return this.talkFieldSpecified;
        }
        set {
            this.talkFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Play {
        get {
            return this.playField;
        }
        set {
            this.playField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PlaySpecified {
        get {
            return this.playFieldSpecified;
        }
        set {
            this.playFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Stop {
        get {
            return this.stopField;
        }
        set {
            this.stopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StopSpecified {
        get {
            return this.stopFieldSpecified;
        }
        set {
            this.stopFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Next {
        get {
            return this.nextField;
        }
        set {
            this.nextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NextSpecified {
        get {
            return this.nextFieldSpecified;
        }
        set {
            this.nextFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Previous {
        get {
            return this.previousField;
        }
        set {
            this.previousField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PreviousSpecified {
        get {
            return this.previousFieldSpecified;
        }
        set {
            this.previousFieldSpecified = value;
        }
    }
}
