//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class objects {
    
    private objectsCamera[] camerasField;
    
    private objectsMicrophone[] microphonesField;
    
    private objectsFloorplan[] floorplansField;
    
    private objectsCommand[] remotecommandsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("camera", IsNullable=false)]
    public objectsCamera[] cameras {
        get {
            return this.camerasField;
        }
        set {
            this.camerasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("microphone", IsNullable=false)]
    public objectsMicrophone[] microphones {
        get {
            return this.microphonesField;
        }
        set {
            this.microphonesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("floorplan", IsNullable=false)]
    public objectsFloorplan[] floorplans {
        get {
            return this.floorplansField;
        }
        set {
            this.floorplansField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("command", IsNullable=false)]
    public objectsCommand[] remotecommands {
        get {
            return this.remotecommandsField;
        }
        set {
            this.remotecommandsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCamera {
    
    private objectsCameraSettings settingsField;
    
    private objectsCameraFtp ftpField;
    
    private objectsCameraDetector detectorField;
    
    private objectsCameraRecorder recorderField;
    
    private objectsCameraAlerts alertsField;
    
    private objectsCameraNotifications notificationsField;
    
    private objectsCameraSchedule scheduleField;
    
    private int idField;
    
    private string nameField;
    
    private string descriptionField;

    private string directoryField;
    
    private int xField;
    
    private int yField;

    private bool flipxField;

    private bool flipyField;

    private bool rotate90Field;

    private int widthField;
    
    private int heightField;
   
    private string resolutionField;
    
    private int ptzField;

    private int newrecordingcountField;

    private string encodekeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string encodekey
    {
        get
        {
            return this.encodekeyField;
        }
        set
        {
            this.encodekeyField = value;
        }
    }

    /// <remarks/>
    public objectsCameraSettings settings {
        get {
            return this.settingsField;
        }
        set {
            this.settingsField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraFtp ftp {
        get {
            return this.ftpField;
        }
        set {
            this.ftpField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraDetector detector {
        get {
            return this.detectorField;
        }
        set {
            this.detectorField = value;
        }
    }

    
    /// <remarks/>
    public objectsCameraRecorder recorder {
        get {
            return this.recorderField;
        }
        set {
            this.recorderField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraAlerts alerts {
        get {
            return this.alertsField;
        }
        set {
            this.alertsField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraNotifications notifications {
        get {
            return this.notificationsField;
        }
        set {
            this.notificationsField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraSchedule schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string directory
    {
        get
        {
            return this.directoryField;
        }
        set
        {
            this.directoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool flipy
    {
        get
        {
            return this.flipyField;
        }
        set
        {
            this.flipyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool flipx
    {
        get
        {
            return this.flipxField;
        }
        set
        {
            this.flipxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool rotate90
    {
        get
        {
            return this.rotate90Field;
        }
        set
        {
            this.rotate90Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resolution {
        get {
            return this.resolutionField;
        }
        set {
            this.resolutionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ptz {
        get {
            return this.ptzField;
        }
        set {
            this.ptzField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int newrecordingcount
    {
        get
        {
            return this.newrecordingcountField;
        }
        set
        {
            this.newrecordingcountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraSettings {
    
    private int sourceindexField;
    
    private string codecField;
    
    private string videosourcestringField;
    
    private string loginField;
    
    private string passwordField;
    
    private string useragentField;
    
    private bool suppressnoiseField;
    
    private bool activeField;

    private bool notifyondisconnectField;
    
    private int frameintervalField;

    private int framerateField;
    
    private string smsnumberField;
    
    private string emailaddressField;
    
    private string ffmpegField;
    
    private bool deleteaviField;
    
    private int micpairField;

    private string maskimageField;

    private string timestampformatterField;
    
    private int timestamplocationField;

    private int desktopresizewidthField;

    private int desktopresizeheightField;

    private string desktopareaField;

    private bool desktopmouseField;
    
    private objectsCameraSettingsYoutube youtubeField;

    private string vlcargsField;

    private bool ptzflipxField;
    private bool ptzflipyField;
    private bool ptzrotate90Field;

    private string ptzurlbaseField;

    private int crossbarindexField;

    private bool resizeField;

    private string namevaluesettingsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string namevaluesettings
    {
        get
        {
            return this.namevaluesettingsField;
        }
        set
        {
            this.namevaluesettingsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool resize
    {
        get
        {
            return this.resizeField;
        }
        set
        {
            this.resizeField = value;
        }
    }

    /// <remarks/>
    public bool desktopmouse
    {
        get
        {
            return this.desktopmouseField;
        }
        set
        {
            this.desktopmouseField = value;
        }
    }

    /// <remarks/>
    public int crossbarindex
    {
        get
        {
            return this.crossbarindexField;
        }
        set
        {
            this.crossbarindexField = value;
        }
    }

    
    /// <remarks/>
    public int sourceindex {
        get {
            return this.sourceindexField;
        }
        set {
            this.sourceindexField = value;
        }
    }
    
    /// <remarks/>
    public string codec {
        get {
            return this.codecField;
        }
        set {
            this.codecField = value;
        }
    }
    
    /// <remarks/>
    public string videosourcestring {
        get {
            return this.videosourcestringField;
        }
        set {
            this.videosourcestringField = value;
        }
    }
    
    /// <remarks/>
    public string login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public string useragent {
        get {
            return this.useragentField;
        }
        set {
            this.useragentField = value;
        }
    }
    
    /// <remarks/>
    public bool suppressnoise {
        get {
            return this.suppressnoiseField;
        }
        set {
            this.suppressnoiseField = value;
        }
    }

    /// <remarks/>
    public bool ptzflipx
    {
        get
        {
            return this.ptzflipxField;
        }
        set
        {
            this.ptzflipxField = value;
        }
    }

    /// <remarks/>
    public bool ptzflipy
    {
        get
        {
            return this.ptzflipyField;
        }
        set
        {
            this.ptzflipyField = value;
        }
    }

    /// <remarks/>
    public bool ptzrotate90
    {
        get
        {
            return this.ptzrotate90Field;
        }
        set
        {
            this.ptzrotate90Field = value;
        }
    }
    
    /// <remarks/>
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }

    /// <remarks/>
    public bool notifyondisconnect
    {
        get {
            return this.notifyondisconnectField;
        }
        set {
            this.notifyondisconnectField = value;
        }
    }    
    
    /// <remarks/>
    public int frameinterval {
        get {
            return this.frameintervalField;
        }
        set {
            this.frameintervalField = value;
        }
    }

    /// <remarks/>
    public int framerate
    {
        get
        {
            return this.framerateField;
        }
        set
        {
            this.framerateField = value;
        }
    }
    
    /// <remarks/>
    public string smsnumber {
        get {
            return this.smsnumberField;
        }
        set {
            this.smsnumberField = value;
        }
    }

    /// <remarks/>
    public string emailaddress
    {
        get
        {
            return this.emailaddressField;
        }
        set
        {
            this.emailaddressField = value;
        }
    }
    
    /// <remarks/>
    public string ptzurlbase
    {
        get
        {
            return this.ptzurlbaseField;
        }
        set
        {
            this.ptzurlbaseField = value;
        }
    }
    
    /// <remarks/>
    public string ffmpeg {
        get {
            return this.ffmpegField;
        }
        set {
            this.ffmpegField = value;
        }
    }
    
    /// <remarks/>
    public bool deleteavi {
        get {
            return this.deleteaviField;
        }
        set {
            this.deleteaviField = value;
        }
    }
    
    /// <remarks/>
    public int micpair {
        get {
            return this.micpairField;
        }
        set {
            this.micpairField = value;
        }
    }

    /// <remarks/>
    public string maskimage
    {
        get
        {
            return this.maskimageField;
        }
        set
        {
            this.maskimageField = value;
        }
    }

    /// <remarks/>
    public string vlcargs
    {
        get
        {
            return this.vlcargsField;
        }
        set
        {
            this.vlcargsField = value;
        }
    }
    
    /// <remarks/>
    public string timestampformatter {
        get {
            return this.timestampformatterField;
        }
        set {
            this.timestampformatterField = value;
        }
    }
    
    /// <remarks/>
    public int timestamplocation {
        get {
            return this.timestamplocationField;
        }
        set {
            this.timestamplocationField = value;
        }
    }
    
    /// <remarks/>
    public objectsCameraSettingsYoutube youtube {
        get {
            return this.youtubeField;
        }
        set {
            this.youtubeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int desktopresizewidth
    {
        get
        {
            return this.desktopresizewidthField;
        }
        set
        {
            this.desktopresizewidthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int desktopresizeheight
    {
        get
        {
            return this.desktopresizeheightField;
        }
        set
        {
            this.desktopresizeheightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string desktoparea
    {
        get
        {
            return this.desktopareaField;
        }
        set
        {
            this.desktopareaField = value;
        }
    }

    
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraSettingsYoutube {
    
    private bool autouploadField;
    
    private bool publicField;
    
    private string tagsField;
    
    private string categoryField;
    
    /// <remarks/>
    public bool autoupload {
        get {
            return this.autouploadField;
        }
        set {
            this.autouploadField = value;
        }
    }
    
    /// <remarks/>
    public bool @public {
        get {
            return this.publicField;
        }
        set {
            this.publicField = value;
        }
    }
    
    /// <remarks/>
    public string tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraFtp {
    
    private bool enabledField;
    
    private string serverField;
    
    private string usernameField;
    
    private string passwordField;
    
    private string filenameField;
    
    private int portField;
    
    private int intervalField;

    private int modeField;
    
    private bool readyField;

    private bool usepassiveField;

    private string textField;
    
    /// <remarks/>
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    public string server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public string text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }
    
    /// <remarks/>
    public int port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    public int interval {
        get {
            return this.intervalField;
        }
        set {
            this.intervalField = value;
        }
    }

    /// <remarks/>
    public int mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    public bool ready {
        get {
            return this.readyField;
        }
        set {
            this.readyField = value;
        }
    }

    /// <remarks/>
    public bool usepassive {
        get {
            return this.usepassiveField;
        }
        set {
            this.usepassiveField = value;
        }
    }

    
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraDetector {
    
    private objectsCameraDetectorZone[] motionzonesField;
    
    private string typeField;
    
    private string postprocessorField;
    
    private int nomovementintervalField;
    
    private int movementintervalField;
    
    private int calibrationdelayField;
    
    private double sensitivityField;
    
    private string colorField;
    
    private bool keepobjectedgesField;
    
    private bool recordondetectField;

    private bool recordonalertField;
    
    private int processeveryframeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("zone", IsNullable=false)]
    public objectsCameraDetectorZone[] motionzones {
        get {
            return this.motionzonesField;
        }
        set {
            this.motionzonesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string postprocessor {
        get {
            return this.postprocessorField;
        }
        set {
            this.postprocessorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int nomovementinterval {
        get {
            return this.nomovementintervalField;
        }
        set {
            this.nomovementintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int movementinterval {
        get {
            return this.movementintervalField;
        }
        set {
            this.movementintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int calibrationdelay {
        get {
            return this.calibrationdelayField;
        }
        set {
            this.calibrationdelayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double sensitivity {
        get {
            return this.sensitivityField;
        }
        set {
            this.sensitivityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool keepobjectedges {
        get {
            return this.keepobjectedgesField;
        }
        set {
            this.keepobjectedgesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordondetect {
        get {
            return this.recordondetectField;
        }
        set {
            this.recordondetectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonalert
    {
        get
        {
            return this.recordonalertField;
        }
        set
        {
            this.recordonalertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int processeveryframe {
        get {
            return this.processeveryframeField;
        }
        set {
            this.processeveryframeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraDetectorZone {
    
    private int leftField;
    
    private int topField;
    
    private int widthField;
    
    private int heightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int left {
        get {
            return this.leftField;
        }
        set {
            this.leftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int top {
        get {
            return this.topField;
        }
        set {
            this.topField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraRecorder {
    
    private int bufferframesField;
    
    private int inactiverecordField;
    
    private int maxrecordtimeField;
    
    private int timelapseField;
    
    private int timelapseframesField;

    private bool timelapseenabledField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int bufferframes {
        get {
            return this.bufferframesField;
        }
        set {
            this.bufferframesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int inactiverecord {
        get {
            return this.inactiverecordField;
        }
        set {
            this.inactiverecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maxrecordtime {
        get {
            return this.maxrecordtimeField;
        }
        set {
            this.maxrecordtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int timelapse {
        get {
            return this.timelapseField;
        }
        set {
            this.timelapseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int timelapseframes {
        get {
            return this.timelapseframesField;
        }
        set {
            this.timelapseframesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool timelapseenabled
    {
        get
        {
            return this.timelapseenabledField;
        }
        set
        {
            this.timelapseenabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraAlerts {
    
    private string alertoptionsField;
    
    private string executefileField;
    
    private int minimumintervalField;
    
    private int objectcountalertField;
    
    private bool activeField;
    
    private string modeField;

    private string numberplatesField;
    
    /// <remarks/>
    public string alertoptions {
        get {
            return this.alertoptionsField;
        }
        set {
            this.alertoptionsField = value;
        }
    }
    
    /// <remarks/>
    public string executefile {
        get {
            return this.executefileField;
        }
        set {
            this.executefileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minimuminterval {
        get {
            return this.minimumintervalField;
        }
        set {
            this.minimumintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int objectcountalert {
        get {
            return this.objectcountalertField;
        }
        set {
            this.objectcountalertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numberplates
    {
        get
        {
            return this.numberplatesField;
        }
        set
        {
            this.numberplatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraNotifications {
    
    private int emailgrabintervalField;
    
    private bool sendemailField;
    
    private bool sendsmsField;
    
    private bool sendmmsField;
        
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int emailgrabinterval {
        get {
            return this.emailgrabintervalField;
        }
        set {
            this.emailgrabintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendemail {
        get {
            return this.sendemailField;
        }
        set {
            this.sendemailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendsms {
        get {
            return this.sendsmsField;
        }
        set {
            this.sendsmsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendmms {
        get {
            return this.sendmmsField;
        }
        set {
            this.sendmmsField = value;
        }
    }
 }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraSchedule {
    
    private objectsCameraScheduleEntry[] entriesField;
    
    private bool activeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
    public objectsCameraScheduleEntry[] entries {
        get {
            return this.entriesField;
        }
        set {
            this.entriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCameraScheduleEntry {
    
    private string startField;
    
    private string stopField;
    
    private string daysofweekField;

    private bool recordonstartField;

    private bool activeField;

    private bool recordondetectField;

    private bool recordonalertField;

    private bool alertsField;

    private bool timelapseenabledField;
  
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stop {
        get {
            return this.stopField;
        }
        set {
            this.stopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string daysofweek {
        get {
            return this.daysofweekField;
        }
        set {
            this.daysofweekField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonstart
    {
        get
        {
            return this.recordonstartField;
        }
        set
        {
            this.recordonstartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordondetect
    {
        get
        {
            return this.recordondetectField;
        }
        set
        {
            this.recordondetectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonalert
    {
        get
        {
            return this.recordonalertField;
        }
        set
        {
            this.recordonalertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool alerts
    {
        get
        {
            return this.alertsField;
        }
        set
        {
            this.alertsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool timelapseenabled
    {
        get
        {
            return this.timelapseenabledField;
        }
        set
        {
            this.timelapseenabledField = value;
        }
    }

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophone {
    
    private objectsMicrophoneSettings settingsField;
    
    private objectsMicrophoneDetector detectorField;
    
    private objectsMicrophoneRecorder recorderField;
    
    private objectsMicrophoneAlerts alertsField;
    
    private objectsMicrophoneNotifications notificationsField;
    
    private objectsMicrophoneSchedule scheduleField;
    
    private int idField;
    
    private string nameField;

    private string directoryField;
    
    private string descriptionField;
    
    private int xField;
    
    private int yField;
    
    private int widthField;
    
    private int heightField;

    private int newrecordingcountField;

    private int portField;
    
    /// <remarks/>
    public objectsMicrophoneSettings settings {
        get {
            return this.settingsField;
        }
        set {
            this.settingsField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneDetector detector {
        get {
            return this.detectorField;
        }
        set {
            this.detectorField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneRecorder recorder {
        get {
            return this.recorderField;
        }
        set {
            this.recorderField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneAlerts alerts {
        get {
            return this.alertsField;
        }
        set {
            this.alertsField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneNotifications notifications {
        get {
            return this.notificationsField;
        }
        set {
            this.notificationsField = value;
        }
    }
    
    /// <remarks/>
    public objectsMicrophoneSchedule schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string directory
    {
        get
        {
            return this.directoryField;
        }
        set
        {
            this.directoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int newrecordingcount
    {
        get
        {
            return this.newrecordingcountField;
        }
        set
        {
            this.newrecordingcountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int port
    {
        get
        {
            return this.portField;
        }
        set
        {
            this.portField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneSettings {
    
    private int sourceindexField;
    
    private int bufferField;
    
    private int samplesField;
    
    private int bitsField;
    
    private int channelsField;
    
    private bool activeField;
    
    private string smsnumberField;
    
    private string emailaddressField;
    
    private string sourcenameField;

    private string usernameField;

    private string passwordField;

    private int typeindexField;
    
    private string ffmpegField;
    
    private bool deletewavField;
    
    private bool decompressField;

    private bool notifyondisconnectField;

    private string vlcargsField;

    private int volumeField;
    
    /// <remarks/>
    public int sourceindex {
        get {
            return this.sourceindexField;
        }
        set {
            this.sourceindexField = value;
        }
    }
    
    /// <remarks/>
    public int buffer {
        get {
            return this.bufferField;
        }
        set {
            this.bufferField = value;
        }
    }
    
    /// <remarks/>
    public int samples {
        get {
            return this.samplesField;
        }
        set {
            this.samplesField = value;
        }
    }
    
    /// <remarks/>
    public int bits {
        get {
            return this.bitsField;
        }
        set {
            this.bitsField = value;
        }
    }
    
    /// <remarks/>
    public int channels {
        get {
            return this.channelsField;
        }
        set {
            this.channelsField = value;
        }
    }

    /// <remarks/>
    public int volume
    {
        get
        {
            return this.volumeField;
        }
        set
        {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }

    /// <remarks/>
    public bool notifyondisconnect
    {
        get
        {
            return this.notifyondisconnectField;
        }
        set
        {
            this.notifyondisconnectField = value;
        }
    }
    
    /// <remarks/>
    public string smsnumber {
        get {
            return this.smsnumberField;
        }
        set {
            this.smsnumberField = value;
        }
    }
    
    /// <remarks/>
    public string emailaddress {
        get {
            return this.emailaddressField;
        }
        set {
            this.emailaddressField = value;
        }
    }
    
    /// <remarks/>
    public string sourcename {
        get {
            return this.sourcenameField;
        }
        set {
            this.sourcenameField = value;
        }
    }

    /// <remarks/>
    public string vlcargs
    {
        get
        {
            return this.vlcargsField;
        }
        set
        {
            this.vlcargsField = value;
        }
    }

    /// <remarks/>
    public string username
    {
        get
        {
            return this.usernameField;
        }
        set
        {
            this.usernameField = value;
        }
    }

    /// <remarks/>
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public int typeindex
    {
        get {
            return this.typeindexField;
        }
        set {
            this.typeindexField = value;
        }
    }
    
    /// <remarks/>
    public string ffmpeg {
        get {
            return this.ffmpegField;
        }
        set {
            this.ffmpegField = value;
        }
    }
    
    /// <remarks/>
    public bool deletewav {
        get {
            return this.deletewavField;
        }
        set {
            this.deletewavField = value;
        }
    }
    
    /// <remarks/>
    public bool decompress {
        get {
            return this.decompressField;
        }
        set {
            this.decompressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneDetector {
    
    private int sensitivityField;
    
    private int nosoundintervalField;
    
    private int soundintervalField;
    
    private bool recordondetectField;

    private bool recordonalertField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sensitivity {
        get {
            return this.sensitivityField;
        }
        set {
            this.sensitivityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int nosoundinterval {
        get {
            return this.nosoundintervalField;
        }
        set {
            this.nosoundintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int soundinterval {
        get {
            return this.soundintervalField;
        }
        set {
            this.soundintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordondetect {
        get {
            return this.recordondetectField;
        }
        set {
            this.recordondetectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonalert
    {
        get
        {
            return this.recordonalertField;
        }
        set
        {
            this.recordonalertField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneRecorder {
    
    private int inactiverecordField;
    
    private int maxrecordtimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int inactiverecord {
        get {
            return this.inactiverecordField;
        }
        set {
            this.inactiverecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maxrecordtime {
        get {
            return this.maxrecordtimeField;
        }
        set {
            this.maxrecordtimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneAlerts {
    
    private string alertoptionsField;
    
    private string executefileField;
    
    private int minimumintervalField;
    
    private bool activeField;
    
    private string modeField;
    
    /// <remarks/>
    public string alertoptions {
        get {
            return this.alertoptionsField;
        }
        set {
            this.alertoptionsField = value;
        }
    }
    
    /// <remarks/>
    public string executefile {
        get {
            return this.executefileField;
        }
        set {
            this.executefileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minimuminterval {
        get {
            return this.minimumintervalField;
        }
        set {
            this.minimumintervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneNotifications {
    
    private bool sendemailField;
    
    private bool sendsmsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendemail {
        get {
            return this.sendemailField;
        }
        set {
            this.sendemailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sendsms {
        get {
            return this.sendsmsField;
        }
        set {
            this.sendsmsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneSchedule {
    
    private objectsMicrophoneScheduleEntry[] entriesField;
    
    private bool activeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
    public objectsMicrophoneScheduleEntry[] entries {
        get {
            return this.entriesField;
        }
        set {
            this.entriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsMicrophoneScheduleEntry {
    
    private string startField;
    
    private string stopField;
    
    private string daysofweekField;

    private bool recordonstartField;

    private bool activeField;

    private bool recordondetectField;

    private bool recordonalertField;

    private bool alertsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stop {
        get {
            return this.stopField;
        }
        set {
            this.stopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string daysofweek {
        get {
            return this.daysofweekField;
        }
        set {
            this.daysofweekField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonstart
    {
        get
        {
            return this.recordonstartField;
        }
        set
        {
            this.recordonstartField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool active
    {
        get
        {
            return this.activeField;
        }
        set
        {
            this.activeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordondetect
    {
        get
        {
            return this.recordondetectField;
        }
        set
        {
            this.recordondetectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recordonalert
    {
        get
        {
            return this.recordonalertField;
        }
        set
        {
            this.recordonalertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool alerts
    {
        get
        {
            return this.alertsField;
        }
        set
        {
            this.alertsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsFloorplan {
    
    private objectsFloorplanObjects objectsField;
    
    private int idField;
    
    private string nameField;
    
    private int xField;
    
    private int yField;
    
    private int widthField;
    
    private int heightField;
    
    private string imageField;
    
    private bool needsupdateField;
   
    /// <remarks/>
    public objectsFloorplanObjects objects {
        get {
            return this.objectsField;
        }
        set {
            this.objectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }

    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool needsupdate {
        get {
            return this.needsupdateField;
        }
        set {
            this.needsupdateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsFloorplanObjects {
    
    private objectsFloorplanObjectsEntry[] objectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
    public objectsFloorplanObjectsEntry[] @object {
        get {
            return this.objectField;
        }
        set {
            this.objectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsFloorplanObjectsEntry {
    
    private string typeField;
    
    private int idField;
    
    private int xField;
    
    private int yField;

    private int angleField;

    private int fovField;

    private int radiusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int angle
    {
        get
        {
            return this.angleField;
        }
        set
        {
            this.angleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int radius
    {
        get
        {
            return this.radiusField;
        }
        set
        {
            this.radiusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int fov
    {
        get
        {
            return this.fovField;
        }
        set
        {
            this.fovField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class objectsCommand {
    
    private int idField;
    
    private string nameField;
    
    private string commandField;

    private string smscommandField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string smscommand
    {
        get
        {
            return this.smscommandField;
        }
        set
        {
            this.smscommandField = value;
        }
    }
}
